# Generated by Django 4.2.13 on 2024-06-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('authors', models.TextField(verbose_name='Autor')),
                ('categories', models.CharField(max_length=100, verbose_name='Categoria')),
                ('publishedDate', models.CharField(max_length=100, verbose_name='Data de Publicação')),
                ('thumbnail', models.TextField(verbose_name='Capa')),
                ('pageCount', models.IntegerField(blank=True, null=True, verbose_name='Número de páginas')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Editora')),
                ('google_books_id', models.CharField(max_length=200, unique=True, verbose_name='ID no Google Books')),
                ('selfLink', models.CharField(max_length=200, verbose_name='Link de detalhes')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('is_open', models.BooleanField(default=True, verbose_name='Pedido em aberto')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.book', verbose_name='Livro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.order', verbose_name='Pedido')),
            ],
        ),
    ]
